### ISSUE TITLE
test/test.py fails trying to verify

### ISSUE THREAD

**Issue by stuartlynne** [pyauth/tsp-client#2]
running test.py fails with this output. 

This is in a Linux Mint 20 system with python 3.8.

 `
EE
======================================================================
ERROR: test_basic_tsp_client_operations (__main__.TestTSPClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 36, in test_basic_tsp_client_operations
    signed = self.signer.sign(message)
  File "/lvm1/home/sl/work/work23/tsr/tsp-client/tsp_client/signer.py", line 65, in sign
    verify_result = self._verifier.verify(tst, nonce=nonce, message_digest=digest)
  File "/lvm1/home/sl/work/work23/tsr/tsp-client/tsp_client/verifier.py", line 173, in verify
    signing_cert = self._extract_signing_cert(signer_info, certificates=certificates)
  File "/lvm1/home/sl/work/work23/tsr/tsp-client/tsp_client/verifier.py", line 123, in _extract_signing_cert
    store = self._get_ca_store()
  File "/lvm1/home/sl/work/work23/tsr/tsp-client/tsp_client/verifier.py", line 98, in _get_ca_store
    store.load_locations(cafile=ca_pem_file, capath=ca_path)  # type: ignore
AttributeError: 'X509Store' object has no attribute 'load_locations'

======================================================================
ERROR: test_set_custom_tsa (__main__.TestTSPClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 60, in test_set_custom_tsa
    signed = self.signer.sign(message, signing_settings=signing_settings)
  File "/lvm1/home/sl/work/work23/tsr/tsp-client/tsp_client/signer.py", line 65, in sign
    verify_result = self._verifier.verify(tst, nonce=nonce, message_digest=digest)
  File "/lvm1/home/sl/work/work23/tsr/tsp-client/tsp_client/verifier.py", line 173, in verify
    signing_cert = self._extract_signing_cert(signer_info, certificates=certificates)
  File "/lvm1/home/sl/work/work23/tsr/tsp-client/tsp_client/verifier.py", line 123, in _extract_signing_cert
    store = self._get_ca_store()
  File "/lvm1/home/sl/work/work23/tsr/tsp-client/tsp_client/verifier.py", line 98, in _get_ca_store
    store.load_locations(cafile=ca_pem_file, capath=ca_path)  # type: ignore
AttributeError: 'X509Store' object has no attribute 'load_locations'

----------------------------------------------------------------------
Ran 2 tests in 0.296s

FAILED (errors=2)

'

**Comment by kislyuk** [comment]
Thanks for the report. This package requires pyopenssl version 20 or later (which provides the method `load_locations`), and previously incorrectly specified the dependency range. I've released v0.1.4 with the change to specify the correct minimal version requirement.
